# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [307]:
import numpy as np
a = np.zeros((1, 100))
print(a)


[[0. 0. 0. ... 0. 0. 0.]]


#### 2.Создать вектор размера 100, заполненный единицами

In [308]:
a = np.ones((1,100))
print(a)

[[1. 1. 1. ... 1. 1. 1.]]


#### 3.Создать вектор размера 100, заполненный числом 3

In [309]:
#без цикла
a = np.zeros((1, 100))
for i in range(100):
    a[0:i]=3
print(a)
#or
b=np.full(100, 3)
print(b)
#or
b = np.eye(100)
b[::]=3
print(b)

[[3. 3. 3. ... 3. 3. 3.]]
[3 3 3 ... 3 3 3]
[[3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 ...
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]
 [3. 3. 3. ... 3. 3. 3.]]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [310]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 5. Поменять 2 строки в матрице

In [311]:
n = int(input())
m = int(input())
a = np.array([[1,2], [2,3], [3,4]])
c = np.array([[1,2], [2,3], [3,4]])
b = c[m:(m+1), :]
a[m:(m+1), :] = a[n:(n+1), :]
a[n:(n+1), :] = b
print(a)

5
5
[[1 2]
 [2 3]
 [3 4]]


# 6. Создать вектор со значениями от 10 до 100

In [312]:
a=np.arange(10,101)
print(a)

[ 10  11  12 ...  98  99 100]


#### 7. Развернуть вектор (первый становится последним)

In [314]:
n = int(input())
a = np.arange(n)
A=-1
for i in range(0, int(n/2)):
    A=a[i]
    a[i]=a[-i-1]
    a[-i-1]=A
print(a)

#or

b = np.arange(n)
b=b[::-1]
print(b)

#or

c = np.ones((10,10))
c[1:-1,1:-1] = 0
print(np.diag(np.arange(1, 5), k=-1))
print(c)  

5
[4 3 2 1 0]
[4 3 2 1 0]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [ ]:
a = np.arange(16)
a = a.reshape((4, 4))
print(a)

#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
a = np.array([ [1, 2, 3, 4, 5] ])
a = np.insert(a, [1, 2, 3, 4], 0)
print(a)

#### 10. Создать 3x3 единичную матрицу

In [ ]:
a = np.eye(3)
print(a)

#### 11. Создать массив 3x3x3 со случайными значениями

In [ ]:
a = np.random.random((3,3,3))
print(a)

#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [ ]:
a = np.random.random((10,10))
max=a.max()
min=a.min()
print(min, max)


#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [ ]:
a = np.random.random(30)
print(a.mean())

#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [ ]:
l = int(input())
w = int(input())
a = np.ones((l, w))
a[1:-1, 1:-1] = 0
print(a)


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [ ]:
# Ромбик
A = np.abs(np.linspace(-2,2,5))[:, np.newaxis]
print(A)
dist_from_center = np.abs(np.linspace(-2,2,5))[:, np.newaxis] + np.abs(np.linspace(-2,2,5))[np.newaxis, :]
dist_from_center

#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [ ]:
z = np.diag(np.arange(1, 5), k=-1)
print(z)

#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [ ]:
a = np.eye(8)
for i in range(8):
    for j in range(8):
        if (i+j)%2==0:
            a[i:i+1, j:j+1]=0
        else:
            a[i:i+1, j:j+1]=1
print(a)


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [ ]:
a = (10*np.random.random((6,7,8))).round()
a = a.flatten()
print(a)
print(a[99:100])

#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [ ]:
a = np.eye(2)
a = np.tile(a, [4, 4])
print(a)

#### 20. Перемножить матрицы 5x3 и 3x2

In [ ]:
a = np.arange(15)
a = a.reshape(5, 3)
b = np.arange(6)
b = b.reshape(3, 2)
print(np.dot(a, b))

#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
N = int(input())
m = int(input())
n = int(input())
a = np.arange(N)
a = a.reshape(m,n)
for i in range(m):
    for j in range(n):
        if 3 < a[i:i+1, j:j+1] < 8:
            a[i:i+1, j:j+1] = -a[i:i+1, j:j+1]
print(a)

#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [ ]:
a = np.arange(5)
a = np.tile(a,[5,1])
print(a)

#### 24. Есть генератор, сделать с его помощью массив

In [ ]:
b = np.arange(15)
a = np.array([i for i in b])
a

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [ ]:
A = np.random.sample(10)
print(A)

#### 26. Отсортировать вектор

In [ ]:
A = (100 * np.random.sample(10)).round()
print(A)
A = np.sort(A)
print(A)

#### 27. Проверить, одинаковы ли 2 numpy массива

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
c = a==b
if c.all() == True:
    print(True)
else:
    print(False)
# and

a = np.array([1,2,4,4])
b = np.array([1,2,3,4])
c = a==b
if c.all() == True:
    print(True)
else:
    print(False)

#### 28. Сделать массив неизменяемым

In [ ]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 10 # выдаст ошибку

#### 29. Найти n наибольших значений в массиве

In [ ]:
n = int(input())
A = (-np.sort(-np.random.randint(1,100, 10)))
for i in range(n):
    print(A[i])

# or

A = np.arange(10000)
np.random.shuffle(A)
print (A[np.argpartition(-A,n)[:n]])

In [ ]:
a = [2, 1]
a.sort()
a

#### 30. Заменить максимальный элемент на ноль

In [ ]:
A = np.random.randint(1,10, 10)
print(A)
A[np.where(A == A.max())] = 0
A

#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [ ]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [ ]:
X = np.arange(4)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(C)


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 34. Напечатать все значения в массиве

In [ ]:
N = int(input())
a = np.random.randint(1, 100, N)
# для выпрямдения массива используем a.flatten() или a.reshape(-1)
for i in range(N):
    print(a[i])

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
n = int(input())
a = np.random.randint(1, 100, 10)
a[abs(a - n).argmin()]


#### 36. Преобразовать массив из float в int

In [ ]:
a = np.arange(10, dtype=np.int32)
a = a.astype(np.float32)
a

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [ ]:
a = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(a):
    print(index, value)

# or

for index in np.ndindex(a.shape):
    print(index, a[index])

#### 38. Случайно расположить p элементов в 2D массив

In [ ]:
n = 5
p = 3
a = np.zeros((n,n))
np.put(a, np.random.choice(range(n*n), p, replace=False), 1)
a

#### 39. Отнять среднее из каждой строки в матрице

In [ ]:
b = np.array([[1,2,3],
              [3,4,4]])
b - b.mean(1)[:, np.newaxis]

#### 40. Отсортировать матрицу по n-ому столбцу

In [ ]:
a = np.random.randint(0, 10, (3,3))
n = 1  # Нумерация с нуля
print(a)
print(a[a[:, n].argsort()])

#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [ ]:
# 0-ые строка или столбец
a = np.random.randint(0, 2, (3,3))
print(a)
if np.linalg.det(a) == 0:
    print("True")
else:
    print("False")
    
# только 0-й столбец    
Z = np.random.randint(0,3,(3,6))
print(Z, ~Z.any(axis=0))
print((~Z.any(axis=0)).any())

#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [ ]:
A = np.zeros(10)
index = np.random.randint(0,len(A),20)
A += np.bincount(index, minlength=len(A))
print(A)

#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [ ]:
w, h = int(input()), int(input())
a = np.random.randint(0,10,(3, w, h))
len(np.unique(a.sum(axis=0)))

#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [ ]:
a = np.random.randint(0,10,(4, 5))
a.sum(-1)

a = np.random.randint(0,10,(2,2,2,2))
print(a)
print(a.sum(0).sum(0))